name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if available)
      run: npm test --if-present
      
    - name: Check build
      run: npm run build --dry-run || echo "Dry run not supported, skipping"

  quick-build:
    runs-on: windows-latest
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Windows version
      run: npm run build:win
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: quick-build-${{ github.sha }}
        path: dist/
        retention-days: 7
