name: Build and Release

on:
  push:
    tags: [ 'v*' ]

# GitHub Actionsの権限設定
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build:win
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: List dist directory (debug)
      run: dir dist
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*.exe
        retention-days: 7
        
  # ポータブル版のビルド（Windows専用）
  build-portable:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build portable version
      run: npm run package
      
    - name: List portable build results
      run: dir dist
      
    - name: Upload portable artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable
        path: dist/beat-archive-win32-x64/
        retention-days: 7

  # タグがpushされた時のリリース作成
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, build-portable]
    runs-on: ubuntu-latest
    
    steps:
    - name: Delete old releases
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          
          // 全てのリリースを取得
          const releases = await github.rest.repos.listReleases({
            owner,
            repo,
            per_page: 100
          });
          
          // 最新の3つのリリース以外を削除
          const releasesToDelete = releases.data.slice(3);
          
          for (const release of releasesToDelete) {
            console.log(`Deleting release: ${release.tag_name}`);
            await github.rest.repos.deleteRelease({
              owner,
              repo,
              release_id: release.id
            });
          }
          
          console.log(`Deleted ${releasesToDelete.length} old releases`);
          
          // 古いタグも削除（最新の3つ以外）
          const tags = await github.rest.repos.listTags({
            owner,
            repo,
            per_page: 100
          });
          
          const tagsToDelete = tags.data.slice(3);
          
          for (const tag of tagsToDelete) {
            try {
              console.log(`Deleting tag: ${tag.name}`);
              await github.rest.git.deleteRef({
                owner,
                repo,
                ref: `tags/${tag.name}`
              });
            } catch (error) {
              console.log(`Could not delete tag ${tag.name}: ${error.message}`);
            }
          }
          
          console.log(`Deleted ${tagsToDelete.length} old tags`);
          
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: List artifacts (debug)
      run: find . -type f -name "*" | head -20
      
    - name: Prepare release files
      run: |
        mkdir -p release-files
        # .exeファイルをコピー
        if [ -d "windows-build" ]; then
          find windows-build -name "*.exe" -exec cp {} release-files/ \;
          echo "Copied .exe files from windows-build"
        fi
        # ポータブル版全体をZIPにパッケージ
        if [ -d "windows-portable" ]; then
          cd windows-portable
          zip -r ../release-files/Beat-Archive-Portable.zip ./*
          cd ..
          echo "Created portable ZIP package"
        fi
        # 結果を表示
        echo "Release files:"
        ls -la release-files/
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-files/*
        draft: false
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
